### ISSUE TITLE
URL to star name having spaces

### ISSUE THREAD

**Issue by axd1967** [Stellarium/stellarium-web-engine#87] opened 2021-05-05 14:48 UTC
Search for star `V537 Lyr`

the link built is

https://stellarium-web.org/skysource/V537 Lyr?fov=0.82770&date=2021-05-05T20:55:44Z&lat=51.04&lng=3.71&elev=0

notice the space, making the link unusable for sharing.

another example: https://stellarium-web.org/skysource/HD 43509?fov=0.95220&date=2021-05-06T20:59:08Z&lat=51.04&lng=3.71&elev=0

![image](https://user-images.githubusercontent.com/3529789/117297119-1fee0a80-ae76-11eb-8617-f33517850cb6.png)

## Workaround
remove the space(s):

- https://stellarium-web.org/skysource/V537Lyr?fov=0.82770&date=2021-05-05T20:55:44Z&lat=51.04&lng=3.71&elev=0
- https://stellarium-web.org/skysource/HD43509?fov=0.95220&date=2021-05-06T20:59:08Z&lat=51.04&lng=3.71&elev=0

**Comment by xalioth** [comment] 2021-05-07 10:01
Thanks that's areal bug indeed! Note that as a temporary workaround you can perfectly remove the space in the URL.

**Comment by xalioth** [comment] 2021-05-13 09:30
Fixed in 6e367ad0

**Closed by xalioth** 2021-05-13 09:30 UTC

**Comment by axd1967** [comment] 2021-05-13 11:30
Looking at the releases, I see very few tags; and in the web interface there is no indication of release information; how can one know when a commit finally reaches the public web version?

**Comment by xalioth** [comment] 2021-05-13 11:41
Currently we don't flag or tag some kind of official releases. It's true that it's missing in the project. One of the issue is that we also have some private code used in the actual deployed version: deployment scripts, server settings, and code for about dialog, adding non-free data sources and also for the code about noctuasky. So adding version tags would not completely solve the problem..

**Comment by xalioth** [comment] 2021-05-13 11:41
(I'm going to deploy an update in a few minutes)

**Comment by axd1967** [comment] 2021-05-13 12:28
I see...

Suggestion: you could easily share a public branch, and merge with a private branch where you can store sensitive stuff and from where you can deploy.

Basically, users want to see which set of issues have been resolved in what version. The public/private aspects are an interesting problem, I'll ponder over those.

Meanwhile, just a date/time indication in the About dialog could be helpful.

(And I'm aware that most users don't really care about version info; but I like working on this subject.)

**Comment by xalioth** [comment] 2021-05-13 12:36
Yes, I agree with the date/time info, I'll look into that.
(I just pushed an update)

**Comment by axd1967** [comment] 2021-05-13 12:55
You know, there is no pressure; as it obliges you to also update that field before deployment, up to you if it is really worth the effort. (To give you an example, I even tag versions of landscapes, see https://github.com/axd1967/vsrug-ls-gr/releases).

I guess you are using partly automated deployment tools, it shouldn't bee to difficult to insert a date during a deployment task.

**Comment by xalioth** [comment] 2021-05-13 13:45
And for your other comment: yes the public branch is the master branch, which is merged into our private branch

**Comment by axd1967** [comment] 2021-05-14 08:50
Test: https://stellarium-web.org/skysource/Sig%20Gem?fov=3.5773&date=2021-05-14T21%3A15%3A22Z&lat=51.04&lng=3.71&elev=0 -> OK!

**Comment by axd1967** [comment] 2021-05-14 08:54
for some reason, something went wrong in the second test of the same star...

**Comment by xalioth** [comment] 2021-05-14 10:10
Hi, yes there was an issue when deploying, I just re-fixed it.

**Comment by axd1967** [comment] 2021-05-14 10:57
See why those version numbers could make a difference ;-) I would know that something went wrong, just by looking at the deployment time :-)

**Comment by axd1967** [comment] 2021-05-14 10:58
https://stellarium-web.org/skysource/SigGem?fov=3.5773&date=2021-05-14T21:16:48Z&lat=51.04&lng=3.71&elev=0 => OK

**Comment by axd1967** [comment] 2021-05-14 11:00
By the way - for Android you _do_ use version information (and IIRC it is mandatory in order to push to the playstore)

![image](https://user-images.githubusercontent.com/3529789/118261731-46cec100-b4b4-11eb-8613-1463a0f0d4e5.png)


https://play.google.com/store/apps/details?id=com.noctuasoftware.stellarium_plus

**Comment by axd1967** [comment] 2021-05-14 12:25
isn't the URL supposed to open the web page with the details visible?


this URL: https://stellarium-web.org/skysource/GaiaDR2521644570041084800?fov=0.39565&date=2021-05-14T21:59:55Z&lat=51.04&lng=3.71&elev=0

does not open with the associated dialog
![image](https://user-images.githubusercontent.com/3529789/118270301-24db3b80-b4c0-11eb-9c02-0c34222d01f3.png)

**Comment by xalioth** [comment] 2021-05-17 07:02
It doesn't work for Gaia stars because I excluded them from the search index. It was making it too large! For the moment I don't plan to add Gaia names int he data base, so maybe I should prevent the creation of links for these..

**Comment by xalioth** [comment] 2021-05-17 07:02
So yes it should be a separate issue, thanks for noticing!!

**Comment by axd1967** [comment] 2021-05-17 09:56
> So yes it should be a separate issue, thanks for noticing!!

OK - I think that issue is now captured in #91 .
